language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
services:
  - redis-server
cache:
  directories:
  - $HOME/.cache/pip/wheels
install:
  - pip install -U pip wheel setuptools
  - pip install 'git+https://github.com/django/channels.git@1.x#egg=channels-benchmark&subdirectory=testproject'
  - pip install -e .[tests]
  - pip freeze
script: py.test
# TODO: setup test coverage tracking service.
# after_success:
#   - codecov
